// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
        return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyC88ga0Q9QSO3goO1psLeGJ8dv-Z-CS_jc',
    appId: '1:709787559096:web:7c2ea0df20a7f7c9dec04d',
    messagingSenderId: '709787559096',
    projectId: 'bsuvotingapp',
    authDomain: 'bsuvotingapp.firebaseapp.com',
    storageBucket: 'bsuvotingapp.firebasestorage.app',
    measurementId: 'G-9GJRXY36RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATbPr7X2zRYYnkQpyZNCOpRFGsePZSqT0',
    appId: '1:709787559096:android:e79d8e3d6a611282dec04d',
    messagingSenderId: '709787559096',
    projectId: 'bsuvotingapp',
    storageBucket: 'bsuvotingapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCciBsv8TK38JJL-_xiLBPNSIWPg5eqIGo',
    appId: '1:709787559096:ios:a2d0665d68e3e444dec04d',
    messagingSenderId: '709787559096',
    projectId: 'bsuvotingapp',
    storageBucket: 'bsuvotingapp.firebasestorage.app',
    iosBundleId: 'com.example.voting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCciBsv8TK38JJL-_xiLBPNSIWPg5eqIGo',
    appId: '1:709787559096:ios:a2d0665d68e3e444dec04d',
    messagingSenderId: '709787559096',
    projectId: 'bsuvotingapp',
    storageBucket: 'bsuvotingapp.firebasestorage.app',
    iosBundleId: 'com.example.voting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC88ga0Q9QSO3goO1psLeGJ8dv-Z-CS_jc',
    appId: '1:709787559096:web:2f2ac0096b8b2b79dec04d',
    messagingSenderId: '709787559096',
    projectId: 'bsuvotingapp',
    authDomain: 'bsuvotingapp.firebaseapp.com',
    storageBucket: 'bsuvotingapp.firebasestorage.app',
    measurementId: 'G-ENV7ENTT89',
  );
}
